### PR TITLE
Adding ability to override ndots for alpine/musl compatability

### PR DESCRIPTION
**Pull request by gregwalters**
I have problems with Alpine / Musl's DNS resolution and need to adjust ndots for compatibility. Lots of community discussion about this out there.

### CODE REVIEW

**Comment by pajikos** [comment]
Hi Greg,
Thank you for your PR. I would actually prefer a more general option using the `dnsConfig` section in `values.yaml`. Your solution overrides the default DNS configuration in a cluster (I'm aware that ndots=5 is a default value, but the administrator might have globally changed it). Therefore, by default, the helm chart should respect the cluster's default DNS configuration and not be forced to value 5.
I hope you understand what I think to do.

```yaml
# Pod's DNS Configuration
# https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-dns-config
# This value is useful if you need to reduce the DNS load: set "ndots" to 0 and only use FQDNs.
dnsConfig: {}
#  nameservers:
#    - 1.2.3.4
#  searches:
#    - ns1.svc.cluster-domain.example
#    - my.dns.search.suffix
#  options:
#    - name: ndots
#      value: "2"
```

and in your statefulset.yaml something like this:

```yaml
    spec:
      {{- if .Values.dnsConfig }}
      dnsConfig: {{- toYaml .Values.dnsConfig | nindent 8 }}
      {{- end }}
```
Regards
Pavel

**Comment by gregwalters** [comment]
Pavel,

Your solution is much cleaner 👏 . Implemented as suggested!

**Comment by pajikos** [comment]
Hi Greg,
thank you for update, please check the location of your changes, I think it should be here:

```yaml
apiVersion: apps/v1
kind: StatefulSet
spec:
  template:
    spec:
    {{- if .Values.dnsConfig }}
      dnsConfig: 
        {{- toYaml .Values.dnsConfig | nindent 8 }}
    {{- end }}
```

**Comment by gregwalters** [comment]
:shame:

You're right again. I had that at the wrong level. Fixed.

**Comment by pajikos** [comment]
thank you

**Pull request merged**
